export const css_configuration = {
    base_body : "flex items-center h-screen w-full bg-teal-lighter font-['Poppins']",
    base_container: "relative w-full bg-white rounded-lg border p-8 m-4 md:max-w-xl md:mx-auto",
    form_container : "grid grid-cols-2 gap-6 mb-24 h-96",
    form_header:"font-medium text-xl align-middle max-h-12",
    form_step:"font-medium text-base text-end align-middle max-h-12",
    field_classes: "text-sm placeholder:text-sm w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:border-blue-500",
    buttons_group : "max-w-xl mx-auto flex justify-end relative",
    radio_button_group: {radio_button:"form-radio text-blue-500 h-5 w-5", radio_button_lable:"inline-flex items-center mr-4", radio_button_span:"ml-1 text-gray-700 text-sm"},
    button:"py-2 px-4 rounded-md bg-sky-500 text-white",
    card_container : "border border-gray-300 rounded-lg max-w-[830px] mx-auto mb-6 font-['Poppins']",
    card_sub_container : "max-h-[320px] py-4 px-6",
    card_box: "flex flex-col h-full justify-between",
    card_details_container : "flex items-start",
    card_logo:"h-12 w-12 mr-2",
    card_job_title: "text-2xl font-normal font-semibold text-black leading-8",
    card_company:"text-base font-normal leading-6 text-black",
    card_location:"text-base font-normal leading-6 text-gray-600 mb-6",
    card_other_details:"text-base font-normal leading-6 text-black mb-2",
    button_container: "flex justify-start space-x-4 mt-5",
    button_fill:"bg-sky-500 hover:bg-sky-500 text-white font-normal py-2 px-4 rounded",
    button_border:"border border-sky-500 text-sky-600 font-normal py-2 px-4 rounded"
 }
